AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  GreenGrass Image Classification
Resources:          
  resourceDefinition:
    Type: AWS::Greengrass::ResourceDefinition
    Properties:
      Name: resourceDefinition
  functionDefinition:
    Type: AWS::Greengrass::FunctionDefinition
    Properties:
      Name: functionDefinition
  imageFunctionsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.amazonaws.com/cloudformation-stacks-us-east-1/aws-greengrass-mxnet-inception/image-classification-lambda.sam.yaml
  groupDefinitionsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.amazonaws.com/cloudformation-stacks-us-east-1/aws-greengrass-mxnet-inception/greengrass-definitions-rpi.sam.yaml
      Parameters:
        FunctionAliasArnParam: !GetAtt imageFunctionsStack.Outputs.FunctionAlias
        ResourceReferenceParam: !Ref resourceDefinition
        FunctionReferenceParam: !Ref functionDefinition
  greenGrassMXNetGroup:
    Type: AWS::Greengrass::Group
    Properties: 
      Name: !Sub GreenGrassMXNetGroup-${AWS::StackName}
      InitialVersion:
        FunctionDefinitionVersionArn: !GetAtt groupDefinitionsStack.Outputs.functionVersionArn
        ResourceDefinitionVersionArn: !GetAtt groupDefinitionsStack.Outputs.resourceVersionArn
Outputs:
  GreengrassGroupID:
    Value: !Ref greenGrassMXNetGroup
    Description: Greengrass Group ID
