AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  GreenGrass Resource and Function definitions
Parameters: 
  FunctionAliasArnParam: 
    Type: String
  ResourceReferenceParam: 
    Type: String
  FunctionReferenceParam: 
    Type: String
  ModelS3UriParam:
    Type: String
Resources:
  rpiVideoInterfaceResourceDefinitionVersion:
    Type: AWS::Greengrass::ResourceDefinitionVersion
    Properties: 
      ResourceDefinitionId: !Ref ResourceReferenceParam
      Resources: 
        - Id: videoCoreSharedMemoryId
          Name: videoCoreSharedMemory
          ResourceDataContainer: 
            LocalDeviceResourceData: 
              GroupOwnerSetting: 
                AutoAddGroupOwner: True
              SourcePath: /dev/vcsm                  
        - Id: videoCoreInterfaceId
          Name: videoCoreInterface
          ResourceDataContainer: 
            LocalDeviceResourceData: 
              GroupOwnerSetting: 
                AutoAddGroupOwner: True
              SourcePath: /dev/vchiq     
        - Id: mlModelId
          Name: mlModelmxnetInception
          ResourceDataContainer:
            S3MachineLearningModelResourceData: 
              DestinationPath: /greengrass-machine-learning/mxnet/inception_bn
              S3Uri: !Ref ModelS3UriParam                    
  rpiImageClassicationFunctionDefinitionVersion:
    Type: AWS::Greengrass::FunctionDefinitionVersion
    Properties: 
      FunctionDefinitionId: !Ref FunctionReferenceParam
      Functions:
        - 
          Id: ImageClassification
          FunctionArn: !Ref FunctionAliasArnParam
          FunctionConfiguration:
            Pinned: True
            MemorySize: 96000 #KB
            Timeout: 15 #seconds
            EncodingType: json
            Environment:
              AccessSysfs: True
              Execution: 
                IsolationMode: GreengrassContainer
              ResourceAccessPolicies: 
                - ResourceId: videoCoreSharedMemoryId
                  Permission: ro
                - ResourceId: videoCoreInterfaceId
                  Permission: ro
                - ResourceId: mlModelId
                  Permission: ro
              Variables: 
                  MXNET_ENGINE_TYPE: NaiveEngine
Outputs:
  resourceVersionArn:
    Value: !Ref rpiVideoInterfaceResourceDefinitionVersion
    Description: Resource logical ARN
  functionVersionArn:
    Value: !Ref rpiImageClassicationFunctionDefinitionVersion
    Description: Function logical ARN    