AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  GreenGrass Image Classification
Resources:
  resourceDefinition:
    Type: AWS::Greengrass::ResourceDefinition
    Properties: 
      Name: resourceDefinition
  videoCoreResourceDefinitionVersion:
    Type: AWS::Greengrass::ResourceDefinitionVersion
    Properties: 
      ResourceDefinitionId: !Ref resourceDefinition
      Resources: 
        - Id: videoCoreSharedMemoryId
          Name: videoCoreSharedMemory
          ResourceDataContainer: 
            LocalDeviceResourceData: 
              GroupOwnerSetting: 
                AutoAddGroupOwner: True
              SourcePath: /dev/vcsm                  
        - Id: videoCoreInterfaceId
          Name: videoCoreInterface
          ResourceDataContainer: 
            LocalDeviceResourceData: 
              GroupOwnerSetting: 
                AutoAddGroupOwner: True
              SourcePath: /dev/vchiq   
  tempPathResourceDefinitionVersion:
    Type: AWS::Greengrass::ResourceDefinitionVersion
    Properties: 
      ResourceDefinitionId: !Ref resourceDefinition
      Resources: 
        - Id: tempPathId  
          Name: tempPath
          ResourceDataContainer: 
            LocalVolumeResourceData: 
              GroupOwnerSetting: 
                AutoAddGroupOwner: True
              SourcePath: /tmp        
              DestinationPath: /tmp                                  
  imageFunctions:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.amazonaws.com/cloudformation-stacks-us-east-1/aws-greengrass-mxnet-inception/image-classification-lambda.sam.yaml
  imageGGFunctionDefinition:
    Type: AWS::Greengrass::FunctionDefinition
    Properties: 
      Name: functionDefinition        
      InitialVersion: 
        Functions:
          - 
            Id: ImageClassificationFunction
            FunctionArn: !GetAtt imageFunctions.Outputs.FunctionAlias
            FunctionConfiguration:
              Pinned: True
              MemorySize: 96000 #KB
              Timeout: 15 #seconds
              EncodingType: json
              Environment:
                AccessSysfs: True
                Execution: 
                  IsolationMode: GreengrassContainer
                ResourceAccessPolicies: 
                  - ResourceId: videoCoreSharedMemoryId
                    Permission: ro
                  - ResourceId: videoCoreInterfaceId
                    Permission: ro
                Variables: 
                    MXNET_ENGINE_TYPE: NaiveEngine              
  greenGrassMXNetGroup:
    Type: AWS::Greengrass::Group
    Properties: 
      Name: GreenGrassMXNetGroup
      InitialVersion:
        FunctionDefinitionVersionArn: !GetAtt imageGGFunctionDefinition.LatestVersionArn
        ResourceDefinitionVersionArn: !GetAtt resourceDefinition.LatestVersionArn
Outputs:
  GreengrassGroupID:
    Value: !Ref greenGrassMXNetGroup
    Description: Greengrass Group ID