AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Lambda function for GreenGrass Image Classification on Python
Resources:
  imageClassificationLambdaFunction: 
    Type: AWS::Serverless::Function
    Properties: 
      FunctionName: !Sub classification-${AWS::StackName}
      Handler: "greengrass_main.function_handler"
      CodeUri: s3://cloudformation-stacks-us-east-1/aws-greengrass-mxnet-inception/aws-greengrass-image-example.zip
      Runtime: "python2.7"
      Timeout: 25
      AutoPublishAlias: GreenGrassAlias
Outputs:
    FunctionArn:
      Value: !GetAtt imageClassificationLambdaFunction.Arn
      Description: imageClassificationLambdaFunction ARN
    FunctionAlias:
      Value: !Ref imageClassificationLambdaFunction.Alias
      Description: imageClassificationLambdaFunction Alias
    FunctionVersion:
      Value: !Ref imageClassificationLambdaFunction.Version
      Description: imageClassificationLambdaFunction Version
